"""Create playing_xi table

Revision ID: 5bdc24935c27
Revises: 1ef11c73dd1f
Create Date: 2026-08-02 20:39:28.120805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bdc24935c27'
down_revision: Union[str, Sequence[str], None] = '1ef11c73dd1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playing_xi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('batting_position', sa.Integer(), nullable=False),
    sa.Column('is_captain', sa.Boolean(), nullable=False),
    sa.Column('is_wicketkeeper', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playing_xi_id'), 'playing_xi', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playing_xi_id'), table_name='playing_xi')
    op.drop_table('playing_xi')
    # ### end Alembic commands ###
