"""Add current players to innings

Revision ID: da8bae1bb8fe
Revises: 2146eb34cbaa
Create Date: 2026-08-06 12:15:38.668146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da8bae1bb8fe'
down_revision: Union[str, Sequence[str], None] = '2146eb34cbaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('innings', sa.Column('current_striker_id', sa.Integer(), nullable=True))
    op.add_column('innings', sa.Column('current_non_striker_id', sa.Integer(), nullable=True))
    op.add_column('innings', sa.Column('current_bowler_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_innings_id'), 'innings', ['id'], unique=False)
    op.create_foreign_key(None, 'innings', 'players', ['current_striker_id'], ['id'])
    op.create_foreign_key(None, 'innings', 'players', ['current_non_striker_id'], ['id'])
    op.create_foreign_key(None, 'innings', 'players', ['current_bowler_id'], ['id'])
    op.create_index(op.f('ix_tosses_id'), 'tosses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tosses_id'), table_name='tosses')
    op.drop_constraint(None, 'innings', type_='foreignkey')
    op.drop_constraint(None, 'innings', type_='foreignkey')
    op.drop_constraint(None, 'innings', type_='foreignkey')
    op.drop_index(op.f('ix_innings_id'), table_name='innings')
    op.drop_column('innings', 'current_bowler_id')
    op.drop_column('innings', 'current_non_striker_id')
    op.drop_column('innings', 'current_striker_id')
    # ### end Alembic commands ###
